### ISSUE TITLE
A way to identify non declared commands

### ISSUE THREAD

**Issue by dudu631** [frisco82/botCommander#8]
Is there a way to show help when user send a command that doesn't exists? Right now it will show help on Empty and errors, but when I try to parse an undeclared command there is no error.

Example:

```
bot.
  .command('do_that')
  .action( a => {
    //some action
  });

let input = 'do_this';
bot.parse(input);
```

Nothing will be output in this scenario.

**Comment by friscoMad** [comment]
It seems I missed that situation 😢 
But it is easy to implement if you want, just use the default action:
```
bot.
  .action( meta => bot.outputHelp(meta)) //Notice this action is at the top level
  .command('do_that')
  .action( a => {
    //some action
  });

let input = 'do_this';
bot.parse(input);
```

**Comment by dudu631** [comment]
Nice! Much simpler than I was doing. As a workaround I was filtering the bot class for BotCommands and verifying the _name property.
